version: '3.8'

services:
  # Laravel (PHP 8.1)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
    - "8000:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: pgsql
    environment:
      POSTGRES_DB: coleta_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Vue + Vite + Pinia + Vue Router
  frontend:
    image: node:20
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5180:5180"
    command: sh -c "npm install && npx cypress install && npm run dev -- --host"
    environment:
    - CHOKIDAR_USEPOLLING=true
    - VITE_POLLING=true
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
